language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: O/GK8rFX67BckPGySZRpknWrPAPpYtZUPEmQVT3vE5YRZ4eEUpbFTwk3WMok6AabQp72hLW+f6jeTUBWnoIzYgj2Aw8Ra7zLknJCri4VvNocaGNk4A1OdBA+nd1ErMHcgevk2isCi7JbfJ/162AOc2gXaDBR7tyHx977dzLhjv0ts6Lnl2Pg62Irjua24DbUbJM6Qgpl8y7LJgN6x1hFrpwQYZjVN2qgHQORWeoodHtkyuEhfoJ7Epo3+2alUl1WeyTDqwtOJYgaX3j8qaE6qvcXybzhW69HaBYf89jUyUDsJgXf9SkS1yGGe8IpGrlYc2scj6CGaqDiqxuLrYB6xRcBwyHK2NLRU7wHq+R3sVFcsOjdcCrxEKLz0uJ2aLkdN6rfKjG53NBemArodboP5+rIjRL89c6uk91DjXXZ0gjzflitXOrRrkroP1y30y/SsKhMeXmlKZO+mTxgUUUeOnRpXbmggi3bHXIlZlN7R8UVItvVRzQt/W/KzzOLR1SxfpvZHiulsl5R9daMmGe+po2pGbYE2goTYpIQcX/CMtsOlJHFd1bGWm+fEgCGh9srA/KERdEJgHAvJYTqViUBD4UBXdz6sbRm7pDEnPNc/lroNJMys/Eoyc3KJvllgSuZB1V597MIykmta7Kh69PhnAI7E8x7QlOZsAzG+N9AXlw=
  app: solitaire9
  on:
    repo: tkshehan/solitaire9
